### ISSUE TITLE
Feature Request: Text Feedback for Locked Blocks

### ISSUE THREAD

**Issue by mallrat208** [Melonslise/Locks#1]
So this is a bit of an odd one. 

Currently when trying to open locked blocks you get an audio cue to indicate that the block is locked. It would be nice if you also (or by config?) got visual feedback using a status update like beds do. Something along the lines of 'The <blockname> is locked' as someone may hear that cue but not realized what it means, especially since they may not see the lock. By making it a status update it wouldn't spam the chatbox, would fade away after a few seconds, and directly conveys why they can't open it.

**Comment by Melonslise** [comment]
Firstly, the issue tracker should not be used for requests. You can either submit a PR, comment on the curse project page or message me directly. As for the request itself, I'm against this kind of feature. It's not realistic and poor design overall in my opinion. I might something like a lock shake effect, but definitely not a message.

**Comment by mallrat208** [comment]
Forbid someone has hearing issues, you are right however, it is your mod. Good luck

**Comment by Melonslise** [comment]
@mallrat208 I'll try to add some better indication other than subtitles

**Comment by MercurialPony** [comment]
Next update will include a sweet lock shake effect. Hopefully this will work for you
