### ISSUE TITLE
Double chests are not supported...

### ISSUE THREAD

**Issue by SwissCheese5** [Melonslise/Locks#10]
The locked side is locked properly. the other side is unaffected.

**Comment by Melonslise** [comment]
Elaborate please. I do not understand what you’re talking about

**Comment by SwissCheese5** [comment]
We have a double chest, we put a lock on one half of it. that side can be opened but the other half of the block can still be opened like normal.

**Comment by Melonslise** [comment]
Please be more attentive next time. I have described how to lock multiple blocks at once both on [the wiki](https://github.com/Melonslise/Locks/wiki/Lock) and in [my spotlight video](https://youtu.be/RPuTYoXPyn0?t=77)
