### ISSUE TITLE
[SOLVED] Using key panels on locked chest with Locks mods dupes items

### ISSUE THREAD

**Issue by Nebula240** [Melonslise/Locks#111]
Using a key panel from security ccraft (https://www.curseforge.com/minecraft/mc-mods/security-craft) on chests locked with the 
will cause the chest to be "destroyed" and dropping items on the ground.

Then it will ask to set up a password. By setting it and opening the chest there will be a new loot table of items generated inside, basically duping items

https://user-images.githubusercontent.com/62150697/134615968-4c0e2799-7978-4a1d-9983-006e956763e9.mp4

.

**Comment by bl4ckscor3** [comment]
Hi Melonslise, SecurityCraft dev here. I investigated this, and it's not an issue with the Locks mod. See https://github.com/Geforce132/SecurityCraft/issues/279
