### ISSUE TITLE
1.12.2 - Adding Door IDs to the Config

### ISSUE THREAD

**Issue by ano19920** [Melonslise/Locks#13]
[locks config.txt](https://github.com/Melonslise/Locks/files/3350081/locks.config.txt)

Minecraft version: 1.12.2-forge1.12.2-14.23.5.2837
Mod version: Locks-2.2.1

I posted a comment about the mod automatically sensing doors from other mods like ConquestReforged due to the high amount of doors. HOWEVER, I went to their website and grabbed a bunch of the door IDs and did it anyway. When I reloaded my game, the doors still weren't working with the locks/keys. I am not sure if I did the IDs wrong, but I copied them and pasted them as is--and they look just like the minecraft IDs already in the config.

Here is a copy and paste of my config file [GitHub says it won't accept ".cfg" files?] I hope this helps your mod!

**Comment by MercurialPony** [comment]
Try the IDs without the variant in square brackets

**Comment by MercurialPony** [comment]
Oh and you don’t need to reload your game. Changes to the config from the mod menu should be applied instantly during runtime

**Comment by ano19920** [comment]
Hmm, maybe a mod conflict is causing my game to not update during runtime, but I restarted minecraft and I can now use the locks on the doors I listed!!! The variant brackets were definitely the problem. Thanks so much for helping me! :D

**Comment by ano19920** [comment]
![2019-07-02_08 43 09](https://user-images.githubusercontent.com/23690411/60517533-794ae880-9ca5-11e9-86db-9df7fb484686.png)
![2019-07-02_08 43 19](https://user-images.githubusercontent.com/23690411/60517543-7cde6f80-9ca5-11e9-92f3-c4812877ee4d.png)

**Comment by MercurialPony** [comment]
No problem. Have fun!
