### ISSUE TITLE
Bibliocraft

### ISSUE THREAD

**Issue by Kirin92** [Melonslise/Locks#16]
Heya :D

I think that would be nice if the bibliocraft chests could be locked. That would be awesome!

**Comment by MercurialPony** [comment]
What’s preventing you from locking them? Some kind of bug? Which version?

**Comment by Kirin92** [comment]
I use your Locks mod version 2.2.1 and I use a Spongeforge Server version 1.12.2

**Comment by MercurialPony** [comment]
Yes well what’s the issue? Make sure you didn’t make any mistakes when adding the ids to the config

**Comment by Kirin92** [comment]
Okay I'll check them again. Maybe there is a typo.

**Comment by MercurialPony** [comment]
Better show me your config

**Comment by Kirin92** [comment]
Lol ok nevermind. I really had a typo. 
https://i.imgur.com/4YIJS4J.png

**Comment by MercurialPony** [comment]
Glad we sorted that out. Btw if you’re in single player, you can totally edit the config in game via the mod options and you don’t need to restart.
