### ISSUE TITLE
Key ring doesn't work (bug?)

### ISSUE THREAD

**Issue by Kirin92** [Melonslise/Locks#17]
Heya...
sorry for bothering you again but I really have a problem and I don't think I can fix that.
The key ring doesn't work properly. I'll show you a .gif what I mean.
https://s3.gifyu.com/images/2019-07-18_09-38-20.gif
The keys disappear and I can't open the lock on the correct locked chest. After I open the ring and click on the space where the key should be, the keys appear again and I can use them.

**Comment by MercurialPony** [comment]
I’ve fixed this issue in the 1.14 version. I’m sorry, but I’m not keen on going back to 1.12 after I almost entirely remade the mod
