### ISSUE TITLE
Keyring makes keys disappear when you open a chest

### ISSUE THREAD

**Issue by Towhead1212** [Melonslise/Locks#19]
when you put keys ona keyring and open a chest, the keys will disappear but if i open the GUI and click on a "invisible key", it reappears

**Comment by malachy1681** [comment]
I have the same issue.  In single-player, the keyring works as expected, but in multiplayer, the keys disappear either after closing the keyring interface or when accessing a block with inventory.

**Comment by Vheko** [comment]
I have the same problem in multi except that the keys do not disappear only graphically but they are deleted. Only in the keychain, and when opening a door / trunk with the keychain it opens the inventory of the keychain.

**Comment by nivthefox** [comment]
I have this problem as well.
