### ISSUE TITLE
 problem with doors and hatches 1.12.2 multi

### ISSUE THREAD

**Issue by Vheko** [Melonslise/Locks#22]
locked doors, make an opening quick closing when clicked on, if it is close to the door, the door opens implicitly making the closure indiscreet

**Comment by MercurialPony** [comment]
I need some more info. What is your mod version and forge version? Does this happen in singleplayer or multiplayer? Could you please upload your server mod config if multiplayer or client mod config if singleplayer. A video of the issue would also be nice.
