### ISSUE TITLE
Craft problem on 1.12.2

### ISSUE THREAD

**Issue by Obseline** [Melonslise/Locks#24]
My game is crashing when I try to make a link between a lock and a key in my workbench. Here is more informations : 

`
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at melonslise.locks.common.crafting.recipe.RecipeLockableCloning.func_77569_a(RecipeLockableCloning.java:70)
	at net.minecraft.item.crafting.CraftingManager.func_180303_b(CraftingManager.java:226)
	at net.minecraft.inventory.SlotCrafting.func_190901_a(SlotCrafting.java:72)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:303)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_184098_a(SourceFile:131)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.inventory.GuiCrafting.func_73864_a(SourceFile:101)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DaelysVakel'/545025, l='MpServer', x=-1810.58, y=73.00, z=-2006.07]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1832,18,-2358), Chunk: (at 8,1,10 in -115,-148; contains blocks -1840,0,-2368 to -1825,255,-2353), Region: (-4,-5; contains chunks -128,-160 to -97,-129, blocks -2048,0,-2560 to -1537,255,-2049)
	Level time: 7804538 game time, 3639605 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityCustomNpc['Hans Egede'/545160, l='MpServer', x=-1804.50, y=77.50, z=-2016.60], MoCEntityLeopard['Leopard'/545162, l='MpServer', x=-1798.99, y=117.00, z=-2077.91], MoCEntityPandaBear['PandaBear'/545088, l='MpServer', x=-1855.40, y=94.50, z=-2026.60], MoCEntityBlackBear['BlackBear'/545216, l='MpServer', x=-1751.00, y=72.63, z=-1959.98], MoCEntityBee['Bee'/545280, l='MpServer', x=-1732.70, y=67.88, z=-2016.61], EntityCustomNpc['Dave Olson'/545089, l='MpServer', x=-1842.50, y=77.00, z=-2007.50], EntityCustomNpc['Olav Sventsen'/545026, l='MpServer', x=-1810.50, y=73.00, z=-2003.50], EntityCustomNpc['Olvia Hasman'/545027, l='MpServer', x=-1811.00, y=77.56, z=-2005.50], MoCEntityMouse['Mouse'/545156, l='MpServer', x=-1797.50, y=34.00, z=-2015.50], EntityCustomNpc['Dan Fridley'/545157, l='MpServer', x=-1803.50, y=68.00, z=-1994.50], MoCEntityRoach['Roach'/545221, l='MpServer', x=-1761.43, y=92.00, z=-2053.42], EntityCustomNpc['Owen Daventri'/545113, l='MpServer', x=-1831.22, y=73.00, z=-1999.47], MoCEntityMouse['Mouse'/545114, l='MpServer', x=-1836.51, y=23.00, z=-1958.85], MoCEntityMouse['Mouse'/545115, l='MpServer', x=-1836.50, y=23.00, z=-1953.51], EntityPlayerSP['DaelysVakel'/545025, l='MpServer', x=-1810.58, y=73.00, z=-2006.07], MoCEntityDragonfly['DragonFly'/545116, l='MpServer', x=-1829.57, y=67.00, z=-1956.23], EntityRabbit['Lapin'/545117, l='MpServer', x=-1819.80, y=128.13, z=-2074.20], EntityCustomNpc['Henrik Brandt'/545119, l='MpServer', x=-1831.50, y=73.50, z=-2009.50], MoCEntityButterfly['ButterFly'/545108, l='MpServer', x=-1837.31, y=70.00, z=-1938.46], MoCEntityFox['Fox'/545109, l='MpServer', x=-1821.42, y=70.00, z=-1926.02], EntityXPOrb['Orbe d'expérience'/545110, l='MpServer', x=-1808.74, y=68.50, z=-1945.20], MoCEntityFirefly['Firefly'/545174, l='MpServer', x=-1799.10, y=67.00, z=-1956.46], EntityCustomNpc['Sara Liamja'/545111, l='MpServer', x=-1819.50, y=68.50, z=-1997.50], MoCEntityButterfly['ButterFly'/545175, l='MpServer', x=-1798.47, y=69.00, z=-1927.37], EntityCustomNpc['Leïna Helmar'/545128, l='MpServer', x=-1829.50, y=80.50, z=-2019.50], EntitySheep['Mouton'/545069, l='MpServer', x=-1877.27, y=111.88, z=-2016.50], MoCEntityRaccoon['Raccoon'/545070, l='MpServer', x=-1856.88, y=103.63, z=-2075.84], EntityRabbit['Lapin'/545071, l='MpServer', x=-1872.97, y=117.13, z=-2044.52], EntityCustomNpc['Lyron Aldforth'/545121, l='MpServer', x=-1824.54, y=69.00, z=-2011.14], EntityCustomNpc['Rengar Berwyn'/545122, l='MpServer', x=-1815.50, y=77.50, z=-2016.50], EntityCustomNpc['Rosa Markisum'/545123, l='MpServer', x=-1830.00, y=73.56, z=-1996.50], EntityCustomNpc['Anders Fleischer'/545125, l='MpServer', x=-1837.50, y=73.00, z=-1994.50], EntityCustomNpc['Keith Al'Mar'/545126, l='MpServer', x=-1825.00, y=80.56, z=-1994.50], MoCEntityBlackBear['BlackBear'/545211, l='MpServer', x=-1754.97, y=67.00, z=-2008.07], MoCEntityBlackBear['BlackBear'/545212, l='MpServer', x=-1754.50, y=94.00, z=-2057.50], EntityPig['Cochon'/545213, l='MpServer', x=-1766.50, y=80.00, z=-2032.55], EntityChicken['Poule'/545214, l='MpServer', x=-1752.65, y=73.00, z=-1943.79], MoCEntityBee['Bee'/545279, l='MpServer', x=-1737.62, y=68.38, z=-2018.64], EntityItem['item.item.egg'/545215, l='MpServer', x=-1752.28, y=73.00, z=-1944.00], MoCEntityMaggot['Maggot'/545072, l='MpServer', x=-1870.50, y=90.00, z=-1952.87], EntitySheep['Mouton'/545203, l='MpServer', x=-1784.52, y=112.00, z=-2062.77]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1514539072 bytes (1444 MB) / 3056054272 bytes (2914 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512m -Xmx4096m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.42 Powered by Forge 14.23.0.2491 Optifine OptiFine_1.12.2_HD_U_E3 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                 | Source                                      | Signature                                |
	|:------ |:-------------------------------------------- |:----------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                                    | 1.12.2                  | minecraft.jar                               | None                                     |
	| UCHIJA | mcp                                          | 9.42                    | minecraft.jar                               | None                                     |
	| UCHIJA | FML                                          | 8.0.99.99               | forge-1.12.2-14.23.0.2491.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                                        | 14.23.0.2491            | forge-1.12.2-14.23.0.2491.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                               | None                                     |
	| UCHIJA | bauercam                                     | 1.13                    | BauerCam-Mod-1.12.2.jar                     | None                                     |
	| UCHIJA | bibliocraft                                  | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar           | None                                     |
	| UCHIJA | conquest                                     | 3.0.2                   | ConquestReforged-3.0.2-mc1.12.2.jar         | None                                     |
	| UCHIJA | blockpalette                                 | 1.5.0                   | ConquestReforged-3.0.2-mc1.12.2.jar         | None                                     |
	| UCHIJA | connect                                      | 1.0.3-mc1.12.2-SNAPSHOT | ConquestReforged-3.0.2-mc1.12.2.jar         | None                                     |
	| UCHIJA | customspawner                                | 3.11.4                  | CustomMobSpawner-3.11.4.jar                 | None                                     |
	| UCHIJA | customnpcs                                   | 1.12                    | CustomNPCs_1.12.2(30Jan19).jar              | None                                     |
	| UCHIJA | movingworld                                  | 1.12-6.342              | movingworld-1.12-6.342-full.jar             | None                                     |
	| UCHIJA | davincisvessels                              | @DVESSELSVER@           | davincisvessels-1.12-6.337-full.jar         | None                                     |
	| UCHIJA | mocreatures                                  | 12.0.5                  | DrZharks MoCreatures Mod-12.0.5.jar         | None                                     |
	| UCHIJA | locks                                        | 2.2.1                   | Locks-2.2.1.jar                             | None                                     |
	| UCHIJA | lunatriuscore                                | 1.2.0.42                | LunatriusCore-1.12.2-1.2.0.42-universal.jar | None                                     |
	| UCHIJA | minema                                       | 3.4                     | Minema-Mod-Unofficial-1.12.2.jar            | None                                     |
	| UCHIJA | moreplayermodels                             | 1.12.2                  | MorePlayerModels_1.12.2(18jan18).jar        | None                                     |
	| UCHIJA | schematica                                   | 1.8.0.169               | Schematica-1.12.2-1.8.0.169-universal.jar   | None                                     |
	| UCHIJA | variedcommodities                            | 1.12.2                  | VariedCommodities_1.12.2(15may18.jar        | None                                     |

	Loaded coremods (and transformers): 
ShaderHookLoader (Minema-Mod-Unofficial-1.12.2.jar)
  info.ata4.minecraft.minema.shaderHook_coremod.ShaderHookInjector
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6292' Renderer: 'Intel(R) UHD Graphics 630'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 24.20.100.6292, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest_1.12.zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6292
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8
[20:37:26] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Nathan\AppData\Roaming\.launchmycraft\launchers\launcher234778\crash-reports\crash-2019-10-15_20.37.25-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
### Game crashed ! ###
`

**Comment by MercurialPony** [comment]
That’s a very strange log you have there, I can’t seem to determine the issue. Can you upload the regular full Minecraft crash report/log?
