### ISSUE TITLE
[suggestion] Loot tables

### ISSUE THREAD

**Issue by TheSexyYeti** [Melonslise/Locks#25]
You should add lock picks to loot tables like chests and mobs drops. And make the weight at which they drop configurable for mobs and chest. Additionally you could add in the configs a whitelist and blacklist so modpack developers can manually add in which mobs or maybe what blocks could drop lockpicks.

**Comment by MercurialPony** [comment]
Sure

**Comment by Dimentive** [comment]
I support this idea (for 1.12.2).

**Comment by MercurialPony** [comment]
I just realized, can't you just use like LootTweaker or  that sort of thing? It'd be a lot more flexible

**Comment by Dimentive** [comment]
Yes, but it’d be easier and more convenient if the mod offered this feature itself.

**Comment by MercurialPony** [comment]
See, the problem is I can realistically only add items to a few loot tables, all of which will probably be vanilla. But if the user wants to add loot to other world generation mods such as, let's say, recurrent complex or some other mod like that, they'd turn to LootTweaker anyway..

**Comment by MercurialPony** [comment]
Added in latest update
