### ISSUE TITLE
It doesn't load on 1.14.4

### ISSUE THREAD

**Issue by sepsol** [Melonslise/Locks#26]
Here's the [latest.log ](https://gist.github.com/SepSol/49327ee978279ad8f112b60882efdcf4)and [debug.log](https://gist.github.com/SepSol/8ca9aebdc02fb2dd502eb1b42ee1d986)

![image](https://user-images.githubusercontent.com/47871887/67866531-55f25600-fb3e-11e9-8b30-369abb86a3c3.png)

Minecraft 1.14.4
Forge 28.1.70
OptiFine HD U F4
Locks 2.3.1.1

**Comment by MercurialPony** [comment]
I haven’t updated it to 1.14.4 yet. You’ll have to play on 1.14.2 for now

**Comment by sepsol** [comment]
Do you have any ETA for when 1.14.4 version will be out? I wanted this for my server, I can't play on 1.14.2.

**Comment by MercurialPony** [comment]
It shouldn’t be hard, but I just can’t get around to it for the time being

**Comment by H4Mm3r** [comment]
Really loved to get it on 1.14.4, nice job !

**Comment by wchen1990** [comment]
If anyone still cares here's a PR for 1.14.4 (#37). I've not tested it extensively myself but a quick test seems like it works fine. I didn't change much other than updating the function calls to use the new mappings and dependencies. There's a jar file in my repo until @Melonslise releases an official version.
