### ISSUE TITLE
I assume im doing something wrong

### ISSUE THREAD

**Issue by Multifarious-1** [Melonslise/Locks#27]
i am attempting to add the chest from iron chests but when i add in the cofig 
iron_chest:diamond_chest
ironchest:diamond_chest
ironchest:diamondchest
etc it does not seem to work am i missing something very new to setting up server it's jsut for my kids but i need a chest lock function to save my sanity -.-
was trying in single player to start with normal chest lock fine

**Comment by MercurialPony** [comment]
Hi! Can you please post your config file for me to take a look?
Also, in game, press F3 and mouse over the block you’d like to add to the config. In the top left corner of the screen you should find the ID of the block. Make sure it’s exactly that ID you’re adding to the config

**Comment by MercurialPony** [comment]
I should add that unless you’re using 1.14, you shouldn’t be editing the config file itself, but doing so from the in game mod menu for configuration

**Comment by Multifarious-1** [comment]
thank you for the quick reply when i look at it with F3 it says ironchest:iron_chest then below that variant diamond
i didn't realize i should be doing it in mod menu will now once i know how to type it in properly 

also as i am running local  forge server for the kids as long as i am op and edit the main settings through the mod menu it will apply to all right ?

Again thanks for the quick reply and your mod is awesome :D

oh and 1.12.2 version 

also sorry slow reply was doing school run i'm Aussie

**Comment by Multifarious-1** [comment]
i reread al the info and re-watched the video you did on this and i realized what i was doing wrong i am very sorry for wasting your time i needed to do ironchest:iron_chest i did not realize the variant was irrelevant your reply pushed me to explore more and understand better thank you and appreciate your efforts i am a tiny bit less of a noob haha

**Comment by MercurialPony** [comment]
Ah right, my bad, on the server you DO want to edit the server config file. The mod menu is for client only. Glad you got it to work!

**Comment by Multifarious-1** [comment]
me to Cheers !
