### ISSUE TITLE
Biomes O' Plenty doors do not accept locks.

### ISSUE THREAD

**Issue by CoryCoryCoryCoryCory** [Melonslise/Locks#28]
I've added the Biomes O' Plenty _doors_ to the config, and yet they will not lock. I know there aren't any typos in the config because I copy and pasted the same names for the _fence gates_ which lock just fine.
Locks 2.2.1

**Comment by MercurialPony** [comment]
Hey. Can you show your config please?

**Comment by CoryCoryCoryCoryCory** [comment]
Sorry, here you go
# Configuration file

general {

    main {
        # Generate every new chest with a random lock
        B:generate_locks=true

        # Length of a new lock
        I:lock_length=12

        # Chance of a lock pick to not break
        D:lock_pick_strength=0.4

        # Blocks that can be locked.
        # Syntax is the mod domain followed by the block's registry name
        S:lockable_blocks <
            minecraft:chest
            minecraft:trapped_chest
            minecraft:ender_chest
            minecraft:wooden_door
            minecraft:iron_door
            minecraft:spruce_door
            minecraft:birch_door
            minecraft:jungle_door
            minecraft:acacia_door
            minecraft:dark_oak_door
            minecraft:trapdoor
            minecraft:iron_trapdoor
            minecraft:fence_gate
            minecraft:spruce_fence_gate
            minecraft:birch_fence_gate
            minecraft:jungle_fence_gate
            minecraft:acacia_fence_gate
            minecraft:dark_oak_fence_gate
            basemetals:gold_trapdoor
            basemetals:gold_door
            basemetals:diamond_trapdoor
            basemetals:diamond_door
            basemetals:emerald_door
            basemetals:emerald_trapdoor
            basemetals:quartz_trapdoor
            basemecustomquartz_door
            basemetals:obsidian_trapdoor
            basemetals:obsidian_door
            basemetals:antimony_trapdoor
            basemetals:antimony_door
            basemetals:bismuth_trapdoor
            basemetals:bismuth_door
            basemetals:copper_trapdoor
            basemetals:copper_door
            basemetals:lead_trapdoor
            basemetals:lead_door
            basemetals:nickel_trapdoor
            basemetals:nickel_door
            basemetals:silver_door
            basemetals:tin_trapdoor
            basemetals:tin_door
            basemetals:zinc_nether_portal
            basemetals:zinc_door
            basemetals:brass:_trapdoor
            basemetals:brass_door
            basemetals:bronze_trapdoor
            basemetals:bronze_door
            basemetals:cupronickel_trapdoor
            basemetals:cupronickel_door
            basemetals:electrum_trapdoor
            basemetals:electrum_door
            basemetals:invar_trapdoor
            basemetals:invar_door
            basemecustompewter_trapdoor
            basemetals:pewter_door
            basemetals:steel_door
            basemetals:adamantine_trapdoor
            basemetals:adamantine_door
            basemetals:coldiron_trapdoor
            basemetals:coldiron_door
            basemetals:platinum_trapdoor
            basemetals:platinum_door
            basemetals:starsteel_trapdoor
            basemetals:starsteel_door
            basemetals:aquarium_trapdoor
            basemetals:aquarium_door
            basemetals:mithril_trapdoor
            basemetals:mithril_door
            biomesoplenty:sacred_oak_door
            biomesoplenty:cherry_door
            biomesoplenty:umbran_door
            biomesoplenty:fir_door
            biomesoplenty:magic_door
            biomesoplenty:mangrove_door
            biomesoplenty:palm_door
            biomesoplenty:redwood_door
            biomesoplenty:willow_door
            biomesoplenty:pine_door
            biomesoplenty:hellbark_door
            biomesoplenty:jacaranda_door
            biomesoplenty:mahogany_door
            biomesoplenty:ebony_door
            biomesoplenty:eucalyptus_door
            biomesoplenty:sacred_oak_fence_gate
            biomesoplenty:cherry_fence_gate
            biomesoplenty:umbran_fence_gate
            biomesoplenty:fir_fence_gate
            biomesoplenty:ethereal_fence_gate
            biomesoplenty:magic_fence_gate
            biomesoplenty:mangrove_fence_gate
            biomesoplenty:palm_fence_gate
            biomesoplenty:redwood_fence_gate
            biomesoplenty:willow_fence_gate
            biomesoplenty:pine_fence_gate
            biomesoplenty:hellbark_fence_gate
            biomesoplenty:jacaranda_fence_gate
            biomesoplenty:mahogany_fence_gate
            biomesoplenty:ebony_fence_gate
            biomesoplenty:eucalyptus_fence_gate
            quark:spruce_trapdoor
            quark:birch_trapdoor
            quark:jungle_trapdoor
            quark:acacia_trapdoor
            quark:dark_oak_trapdoor
            quark:custom_chest
            quark:custom_chest_trap
            ironchest:iron_chest
         >

        # Maximum allowed volume of a single lock
        I:lockable_volume=20

        # Open locks can be removed with an empty hand while sneaking
        B:remove_locks=true

        # Locked blocks cannot be destroyed in survival mode
        B:unbreakable_locks=true
    }

    client {
        # Enable the client user interface when placing a lock
        B:enable_cui=true
    }

}

**Comment by MercurialPony** [comment]
Sorry for the delay, are you still getting this issue with the latest version?

**Comment by samasiassa** [comment]
> Sorry for the delay, are you still getting this issue with the latest version?

fun fact is, the issue still exists

config works with other mods like rustic, chinese workshops, mist etc. but not with biomes o plenty
