### ISSUE TITLE
[1.12.2] Strange rendering bug – Locks freaking out

### ISSUE THREAD

**Issue by Dimentive** [Melonslise/Locks#29]
[**Video.**](https://giant.gfycat.com/GrandioseAncientGibbon.webm)

As you can see, the locks visually jump around when I’m either moving or looking around. If I stand completely still and also don’t move my view, the locks are still as they should be, but once I start moving either my character or my view, the locks start freaking out again.

Such an obvious bug would probably have been fixed already, so I’m assuming this doesn’t happen if Locks is the only mod installed. There’s probably a mod conflict going on here. At first, I thought it was MalisisDoors since it completely changes how doors work, but then I noticed that this bug also occurs on locks placed on chests, and MalisisDoors doesn’t change chests, so it’s most likely a different mod conflicting.

[Here is my mod list.](https://pastebin.com/raw/GqtNf8XD) I’ve got a _lot_ of mods installed. I could try to narrow it down, but perhaps you might know what mod could be causing this?

(I am not using OptiFine.)

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Locks:** 2.2.1 (latest for 1.12.2)

**Comment by Dimentive** [comment]
In an attempt to narrow it down, I’ve spent the past few hours adding my mods in groups to try to figure out what mod is causing this problem.

Then, I came across a new issue.

**Locks are now transparent!**
![2020-01-07_20 23 31](https://user-images.githubusercontent.com/34230933/71922871-16726680-318c-11ea-8f4d-efba6ffe4cda.png)

This happened after I added the following mods to my test pack (yes, I know it’s still a lot of mods):

![1](https://user-images.githubusercontent.com/34230933/71922901-2c802700-318c-11ea-9d1e-e18eeca5e98a.png)
![2](https://user-images.githubusercontent.com/34230933/71922902-2c802700-318c-11ea-9c6e-d16deb89af53.png)
![3](https://user-images.githubusercontent.com/34230933/71922903-2c802700-318c-11ea-8f18-15bf40b59b63.png)

**Comment by Dimentive** [comment]
With a completely different set of mods, the locks are now completely black—similar to #32, but they’re always black, regardless of the angle you’re viewing them at.

![2020-01-07_21 32 41](https://user-images.githubusercontent.com/34230933/71927219-4bcf8200-3195-11ea-85d8-2243f5d7cebe.png)

**Comment by Dimentive** [comment]
After five hours of tedious testing, I haven’t been able to replicate the original issue by adding my mods in groups. Now, I’ve tested all my mods—just not at the same time—and I still haven’t been able to replicate it. It must be some strange mod conflict between at _least_ two separate mods and Locks. I have no clue, but it is extremely annoying. I wouldn’t even mind transparent or completely black locks, but locks that freak out and won’t stand still are too distracting to be viable, so unfortunately, I have to stop using this mod. 😔

**Comment by Dimentive** [comment]
New revelation: The locks appear fine in my world, aside from being transparent, if I simply go somewhere else, but in the main area (my base), the locks freak out like in the original post, shown by [the video](https://giant.gfycat.com/GrandioseAncientGibbon.webm).

I’ll try removing stuff one by one, unclaiming and unloading chunks, and placing doors or chests with locks in different locations to try to figure out what the problem is.

**Comment by Dimentive** [comment]
New revelation: The locks appear fine in my world, aside from being transparent, if I simply go somewhere else, but in the main area (my base), the locks freak out like in the original post, shown by [the video](https://giant.gfycat.com/GrandioseAncientGibbon.webm).

I’ll try removing stuff one by one, unclaiming and unloading chunks, and placing doors or chests with locks in different locations to try to figure out what is causing this problem. Looks like all those hours of testing with different mods was just a waste of time.

**Comment by Dimentive** [comment]
I believe I figured it out! So, the location of the base is extremely far away from the world spawn. The coordinates of the base are X: 6673 Y: 75 Z: 1303381.

The Z coords specifically are very large. This is because when I created the world, I teleported ridiculously far away from the world spawn trying to find a nice village to make a base. If I teleport to the world spawn or anywhere with a small Z coordinate value, the locks are fine. They’re not even transparent anymore! But at the base, the locks are freaking out as shown in [the video](https://giant.gfycat.com/GrandioseAncientGibbon.webm).

Even when I unload and unclaim every chunk in the world and fly or teleport far away from the base, the locks still freak out, even though nothing that I’ve placed is loaded. Yet, if I teleport to the world spawn, the locks are fine.

The Locks mod must be freaking out at this large Z value. I don’t know why, but it’s the coordinates that are making the locks act so strangely.

Do you think you can identify the issue and fix it in the 1.12.2 version of the mod? If you could, I would absolutely love you more than I love my family. This issue is really distracting, and while the mod is the one mod my brother and I have been looking for for our world, this bug is so distracting that we can’t use the mod, and we can’t just move the entire town we’ve built.

If you could fix this, that would be _**fantastic!**_

**Comment by Dimentive** [comment]
If you fix this bug, I’ll definitely donate (if you’ve got a PayPal or Patreon)! 😃

**Comment by MercurialPony** [comment]
That is extremely weird. I’ll take a look at it when I get the chance. Thanks for investigating

**Comment by Dimentive** [comment]
Yea no prob

**Comment by MercurialPony** [comment]
I believe I've been able to fix the jittering bug. Expect a release soon with several other fixes and features!

**Comment by Dimentive** [comment]
Fantastic! Thank you. ❤️

**Comment by Dimentive** [comment]
Thank you so, so much for the fix!

Do you have a Patreon?

**Comment by MercurialPony** [comment]
Nope, sorry
