### ISSUE TITLE
Levers can be used to open Locked Doors without a key.

### ISSUE THREAD

**Issue by RealMVC** [Melonslise/Locks#3]
If you place a lever near a locked door, and activate it, then the door will open regardless of if it is locked or not. I am in Forge version 2768 and am running Minecraft 1.12.2.

**Comment by Melonslise** [comment]
Not strictly a bug, but should be implemented. Most likely in the next big update.

**Comment by MercurialPony** [comment]
After looking into it, I doubt I'll be able to add something like this or if this is even possible. Unless someone is willing to help

**Comment by imanairconditioner** [comment]
I have this issue too, running 1.14.4 2.5

**Comment by MercurialPony** [comment]
Cool thanks for downvoting my reply. If you're so smart, go ahead and add this feature yourself as a PR, I'd be glad honestly

**Comment by NayosVieurer** [comment]
hey mate. Just so you know, I'm a rookie on Minecraft modding, but, is there any way, when you apply the lock to a door/chest, to change it. I'm taking for reference what has been done on Immersive Engineering, with the multiblock system.

**Comment by S0LiD-ST4T3** [comment]
i'm not an expert, or at all experienced with minecraft modding or java coding, but what if you simply add a segment of code to not accept redstone input while the door is locked, and accept it while unlocked?

[REDSTONE INPUT]

IF LOCKED = TRUE THEN END
IF LOCKED = FALSE THEN [PASS TO REST OF REDSTONE INTERACTION CODE]

basically intercept redstone and just.... make it do nothing while locked, but do whatever it does normally when unlocked.


again, no idea what i'm saying.
### please don't hurt me! _whimper_
