### ISSUE TITLE
[1.12.2] [Suggestion] Wildcards for the config

### ISSUE THREAD

**Issue by Dimentive** [Melonslise/Locks#30]
It would take an extremely long time to add all the doors, chests, gates, etc., to the config when playing a large modpack. My suggestion is a wildcard feature that lets you use an asterisk (`*`) as a wildcard.

Examples:

* `engineersdoors:*` would accept any block from Engineer’s Doors.
* `extratrees:doors.*` would accept any block from Extra Trees that has an item ID which starts with `doors`.
* `forestry:*_chest` would accept any block from Forestry that has an item ID which ends in `_chest`.
* `*` would accept all blocks in the game (which should _not_ be used; it’s just an example).

Is this something you could implement? It would make it take much less time to add doors to the config! 💙

**Comment by MercurialPony** [comment]
That’s not a bad idea. I will look into adding this

**Comment by MercurialPony** [comment]
Done. Expect this in the next update

**Comment by Dimentive** [comment]
Sweet, thanks! 💙

**Comment by MercurialPony** [comment]
No, no, no. Don't close issues until I push the update first

**Comment by Dimentive** [comment]
Oh, sorry.

**Comment by Dimentive** [comment]
Thank you so much for the fix! You’re an incredible developer! 💙

**Comment by Dimentive** [comment]
Thank you so much for adding this! You’re an incredible developer! 💙
