### ISSUE TITLE
[1.12.2] Lighting bug on locks when viewed from certain angles

### ISSUE THREAD

**Issue by Dimentive** [Melonslise/Locks#32]
[**Video 1.**](https://giant.gfycat.com/ColossalAmbitiousCrab.webm)

[**Video 2.**](https://giant.gfycat.com/GlumGlossyFlee.webm)

As you can see in the video 1, the lock on the door turns black when viewed from side angles. However, as you can see in video 2, this doesn’t always happen. Even though it was the same door with the same lock, it just stopped happening for some reason, yet it still happens to another door somewhere else.

This was tested in an instance where the only mod installed was Locks; not a single other mod was installed.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2847 (latest for 1.12.2)
* **Locks:** 2.2.1 (latest for 1.12.2)

**Comment by MercurialPony** [comment]
Found a fix for this too \o/

**Comment by Dimentive** [comment]
Great! 👍

**Comment by Dimentive** [comment]
Great! 👍

When do you think the update will be released? And will it be for 1.12.2 too, like the last update?

**Comment by MercurialPony** [comment]
I'm not sure. I've been adding all the changes to the 1.14 version and I still want to add a few major features. Backporting to 1.12 (yikes) will take even longer..

**Comment by Dimentive** [comment]
Thank you for the fix! 😄👍
