### ISSUE TITLE
custom pin number for locks

### ISSUE THREAD

**Issue by publicXEZ** [Melonslise/Locks#35]
i feel like this mod is great for adventure maps but as far as we have static number of pins for every lock, school's classroom and weapon locker protected with identical locks every time. one of the possible solutions is to add tiered locks that can hold up to #{n} pins and just add pins to lock somehow, maybe just by adding golden nuggets to lock in crafting layout (routine way) or with a help of the special lock creation workbench (way of increasing complexity)

**Comment by MercurialPony** [comment]
I wanted to add tiered locks in the next update. For now just change the lock length config value every time you place a lock in order to achieve the same effect
