### ISSUE TITLE
[Help] Trying to edit the config file.

### ISSUE THREAD

**Issue by lodgingthunder** [Melonslise/Locks#36]
I am currently attempting to edit the config file to add some doors from the DecoCraft mod. However instead of just an item id decocraft also uses the block type tag to differentiate between items. As an example decocrafts vault door is like the other props in the mod props:props as the item id and the block type tag that differentiates it is 1444 does anyone know how to do this or if this is even possible.
Thanks.

**Comment by MercurialPony** [comment]
What is a block type tag?
