### ISSUE TITLE
Keys Disappear with Keyring

### ISSUE THREAD

**Issue by dodgycoffee** [Melonslise/Locks#4]
I saw a similar issue on the cure page, but decided to open a proper github bug report.

What I've been seeing is when using key(s) in the keyring, after a while the key will seemingly vanish. The keyring will look like a blank keyring, looking inside shows nothing. However if I click where the key was, and move it back to inventory, key comes back. I had this happen with 3 different keyrings (same key) over the course of a single 3-hour play session.

My friend on the other hand (same server) had an issue where his key just disappeared completely never to be seen again. Which is more like the reports on the curse thread. I tried to have him click to find an invisible key, but no such luck. It was gone gone.

So there is definitely something up with the keyring specifically where it is forgetting it has keys.

**Minecraft:** 1.1.12
**Mod Version:** Locks-2.2.1
**Forge:** 14.23.5.2815
**Multiplayer:** Yes

**Comment by Melonslise** [comment]
Hmm that's very strange. I couldn't re-create this bug in my game. Can you list the mods you played with? Can you also describe the occurrence of the bug in more detail?

**Comment by dodgycoffee** [comment]
@Melonslise I don't really have much more detail. It disappeared for me at seemingly random times just normal game playthrough. I can however provide the exact modpack we are using. This should give you all the mods and configs we use.

I added the mod to the pack just last night, and experienced disappearing keys at least 4 times in 3 hours. Keys in normal hotbar are fine. I don't know if this matters, but these issues are happening on a multiplayer server. If you tested in SP and couldn't reproduce, it is possible its a MP bug specifically.

https://onetimesecret.com/secret/4jnsh3hsji451kg1axoorwjidfds4hz

**Comment by Loriborn** [comment]
@Melonslise I can confirm this is happening to me as well on our server.

**Comment by Loriborn** [comment]
This particularly happens when opening a chest, which will immediately change the keyring from the "x number of keys" sprite, to the blank sprite, visually emptying it, even if the contents still have the keys, albeit invisibly. Shift-left clicking to remove the keys brings them into the inventory, and closing the inventory makes them visible again.

**Comment by Melonslise** [comment]
Uploading to curse. Should be fixed now
