### ISSUE TITLE
World Load Crash

### ISSUE THREAD

**Issue by WenXin20** [Melonslise/Locks#40]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Locks v2.4`

I created a new world in singleplayer and immediately crashed.
[Crash Report](https://gist.github.com/WenXin20/0a7ecc4a5dcdcb208ef63ea3d1a50f7e)

**Comment by MercurialPony** [comment]
Could you try to run just this mod without other mods?

**Comment by WenXin20** [comment]
Looks like Optifine is the one causing it to crash. Is that something that can be fixed?

**Comment by MercurialPony** [comment]
Yes, I'll try
