### ISSUE TITLE
Missing config option to set strength of lockpicks

### ISSUE THREAD

**Issue by Lucky-Red** [Melonslise/Locks#41]
The setting to change the chance of lockpicks to break seems to be missing from the config as of version 2.4
Is this an intentional design choice?

**Comment by MercurialPony** [comment]
If you read the changelog, you'd know that this value is now stored individually in each item's nbt. You can change the nbt by either by using an editor or doing something like /give locks:lockpick{Strength:x} where x is your desired strength

**Comment by MercurialPony** [comment]
I'm going to add a default config option for these so that any newly made lock picks and locks would have their nbt values set to the default value specified in the config
