### ISSUE TITLE
Locks don't generate on chests in superflat worlds

### ISSUE THREAD

**Issue by Greg-21** [Melonslise/Locks#42]
I tried with multiple superflat worlds in multiple Minecraft versions, and in the ones from Minecraft 1.14.4–1.16.1 I couldn't find literally any locked chest, even when I changed the "Generation Chance" config option to value "1.0" at some point, whereas in the ones from Minecraft 1.12.2 the lock generation worked correctly.

I was able to reproduce this issue on the following configurations:
* Minecraft versions: 1.16.1, 1.15.2, 1.14.4
* Locks versions: 2.4 for MC 1.16.1, 2.4 for MC 1.15.2, 2.4 for MC 1.14.4
* Forge versions: 32.0.75, 31.2.0, 28.2.0

**Comment by MercurialPony** [comment]
You are very right, for some reason it only happens to superflat worlds! I will look into this soon

**Comment by MercurialPony** [comment]
Ok, it seems there's not that much I can do about this issue, it's more of a forge/minecraft limitation. I could always use some core mod hacks, but I'd rather not for such a small feature

**Comment by Greg-21** [comment]
If the fix requires the use of JS coremod hacks, and I don't like JS coremods (Mixin even much more), I'll be OK without the fix for this issue.

Anyway, wouldn't you be able to submit new hooks for Forge, and if they are accepted and merged, call them from this mod (instead of using "private" JS hacks)? I think other modders could also benefit from them.

**Comment by MercurialPony** [comment]
Hah be warned that my mod already uses a bunch of js hacks to get some features working.

Anyway, yes, I probably could submit a pr to forge, but I'd much rather not. It's a massive hassle even just to format them correctly, and it takes a really long time to get them approved

**Comment by MercurialPony** [comment]
Even then, they'd only be available on the newest forge version, while all the other versions will still be stuck with coremod hacks

**Comment by Greg-21** [comment]
Yeah, I know that your mod already has some coremod hacks, but they had existed even before I found out about the mod, so I had no influence on them. I have to accept that fact. Or if you are very bored someday, you can port them over directly to Forge ;)

**Comment by Greg-21** [comment]
Yeah, I know that your mod already has several coremod hacks, but they had existed even before I found out about the mod, so I had no influence on them. I have to accept that fact. Or if you are very bored someday, you can port them over directly to Forge ;)
