### ISSUE TITLE
Crash an world loading (server)

### ISSUE THREAD

**Issue by agentwolf88** [Melonslise/Locks#43]
https://pastebin.com/QXZ3DB6x

**Comment by MercurialPony** [comment]
I already fixed this issue. Try getting the latest build from curse and try again

**Comment by agentwolf88** [comment]
I used the latest version. 2.4 for 1.12.2

**Comment by MercurialPony** [comment]
I know, but I actually uploaded a fix under the same version yesterday

**Comment by MercurialPony** [comment]
Please, let me know if that worked for you @agentwolf88
