### ISSUE TITLE
Shulker Boxes cannot be locked

### ISSUE THREAD

**Issue by WenXin20** [Melonslise/Locks#45]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Locks v2.4`

Shulker Boxes are currently unable to be locked.

**Comment by MercurialPony** [comment]
Have you tried adding them to the config?

**Comment by WenXin20** [comment]
Oh, no, I didn't realize that was a config option. I'll give that a try.

**Comment by MercurialPony** [comment]
I might add them to the config by default in the next update anyway, just in case

**Comment by WenXin20** [comment]
Sounds good!
