### ISSUE TITLE
Mod Corrupts Recipes in Other Mods

### ISSUE THREAD

**Issue by chronicChthonic** [Melonslise/Locks#52]
**After more experimentation, this mod is not the cause of this issue. Or at least, not the sole cause.**

Installing the locks mod corrupts some recipes that use items from other mods. Not all recipes are affected.

Recipes listed in the recipe book do not seem to change, but certain items will not work in recipes or will yield the wrong item.

Example: (Patchouli book for the Japanese Food Mod results in Oak Planks)
<img width="308" alt="Capture" src="https://user-images.githubusercontent.com/68923394/89607023-7e328200-d83f-11ea-9f9c-dfd6b9b9f9ca.PNG">

**Comment by MercurialPony** [comment]
This is extremely strange. Are you sure it's my mod's issue?
