### ISSUE TITLE
[1.15.2][Multiplayer] Crash on attempting to unlock an lock

### ISSUE THREAD

**Issue by dreckz** [Melonslise/Locks#56]
Forge Version: 31.2.35
Locks mod: 2.5.1

Crash occurred in another dimension on my multiplayer server

[crash-2020-08-18_14.28.35-server.txt](https://github.com/Melonslise/Locks/files/5092676/crash-2020-08-18_14.28.35-server.txt)

**Comment by MercurialPony** [comment]
This crash log you provided has nothing to do with my mod by the looks of it. From what I can see your server was too slow to process a single tick and thus it crashed (which is a default mc feature). I don't see anything at all pointing to my mod
