### ISSUE TITLE
Recipes conflict with other mods (immersive engineering_stick_iron)

### ISSUE THREAD

**Issue by mostwantedpwnz** [Melonslise/Locks#57]
Recipes conflict with other mods (immersive engineering_stick_iron)

Trying to create a blank key with iron ingots and it creates iron stick since the recipe conflicts with that recipe sadly, so I can't create blank keys, any way to make an alternative and maybe add recipe for locks

**Comment by MercurialPony** [comment]
Recipe conflicts between mods are bound to happen at some point to any mod. Have you tried minetweaker or no more recipe conflicts mod?

**Comment by mostwantedpwnz** [comment]
> Recipe conflicts between mods are bound to happen at some point to any mod. Have you tried minetweaker or no more recipe conflicts mod?

I tried to use recipe conflict mod but it seems its only for 12.2 and the other one is way to confusing to set up for a basic server, i don't even like adding mods that make you learn to play and this other recipe mod is to confusing for my taste.

**Comment by Greg-21** [comment]
If I can just add my two penn'orth, TheIllusiveC4's Polymorph mod solves the problem of recipe conflicts and is for Minecraft 1.15.2+

**Comment by Greg-21** [comment]
If I can just add my two penn'orth, TheIllusiveC4's Polymorph mod solves the problem of recipe conflicts and is for Minecraft 1.15.2+. Also, you can simply use data packs to adjust modded recipes, just like the vanilla ones.

**Comment by MercurialPony** [comment]
Recipes have been changed so it shouldn't be a problem. If it still is, use a mod that fixes these conflicts as stated above
