### ISSUE TITLE
Bypass Lock

### ISSUE THREAD

**Issue by Mourad788** [Melonslise/Locks#58]
I explain to you my server is a public survival server so players can find in nature chests with a padlock on them so they need a lockpick for that but I found two ways to get around that

We can bypass the lock with a hopper or with just a double chest so there is a video that will explain how to do it and I would like to know if it is possible to fix it please.

I know I could just blacklist the hoppers but for the other problem how do I do?

https://www.youtube.com/watch?v=xARX5r1kF_Q

**Comment by Mourad788** [comment]
up

**Comment by Eowomir7** [comment]
This issue has already been discussed. scroll down to issue #11 in the issues list
