### ISSUE TITLE
Randomly generated locks do not obey configuration for lock length

### ISSUE THREAD

**Issue by duely** [Melonslise/Locks#6]
Unless I'm misunderstanding the nature of the configuration option, it would appear that

https://github.com/Melonslise/Locks/blob/a91573c100dbba32badd9166bf7542bd373faa5b/src/main/java/melonslise/locks/common/event/LocksEvents.java#L120

uses a randomly selected size rather the value set in the configuration.

Alternately, if this was intended, it would be great if you could configure the upper and lower bounds of the locks.

**Comment by Melonslise** [comment]
Yes, it was intended. I’ll try to add the requested feature at some point.

**Comment by Melonslise** [comment]
Enjoy!
