### ISSUE TITLE
(NOT A REAL BUG/ISSUE) Wiki Screenshot Resourcepack

### ISSUE THREAD

**Issue by S0LiD-ST4T3** [Melonslise/Locks#68]
### This is not a problem with the mod whatsoever.
**i just have one simple question...**

### What is the resource pack/texture pack used in the screenshots on the Wiki page?

i know this is such a retarded thing to do, but i don't feel like shredding this git just to find the details.

**Comment by Rayrsn** [comment]
You could have at least tried to read the first page, It's [Conquest Reforged](https://minecraft.curseforge.com/projects/conquest-reforged)
![](https://i.imgur.com/5vb2HVC.png)

**Comment by MercurialPony** [comment]
Or the main page on curse...
