### ISSUE TITLE
1.16.5 item rendering creative inventory

### ISSUE THREAD

**Issue by SuomiIkuisesti** [Melonslise/Locks#73]
keyring item crashes the game all the time.

log https://paste.ee/p/TinJF#DC65rZO5S5bECvVNL7n4hopgVSsifyUd

**Comment by agentwolf88** [comment]
The mod isnt updated to 1.16.5. :(

**Comment by SuomiIkuisesti** [comment]
> The mod isnt updated to 1.16.5. :(

most mods work within old versions of 1.16

**Comment by ghost** [comment]
Will you be updating it soon? If so, when?
