### ISSUE TITLE
crash in 1.16

### ISSUE THREAD

**Issue by lordi-erez** [Melonslise/Locks#75]
https://gist.githubusercontent.com/natanfudge/a88d4343e9e5ddea69b2908b47bd2857/raw/4ca9deca5b23dbbaa500f6b35c8531cc17fd69d5/crash.txt
here;s the log

it crashes as soon as i enter the world

**Comment by DcNdrew** [comment]
Same here. 1.16.5.

**Comment by arBorghi** [comment]
I have the same issue trying to load the world. 
[Locks crashlog.txt](https://github.com/Melonslise/Locks/files/6072275/Locks.crashlog.txt)

**Comment by SuomiIkuisesti** [comment]
Same...

**Comment by AterAnimAvis** [comment]
The issue is this mod targets a forge build in the **breaking changes window** (version `1.16.2-33.0.5`), as of version `1.16.2-33.0.21` the method `LazyOptional#map` was renamed to `LazyOptional#lazyMap`.

This should be fairly simple to fix, bump the forge version and change the reference from `map` to `lazyMap`.

> Build: 1.16.2-33.0.21 - Tue Aug 25 01:11:38 GMT 2020
>	gigaherz:
>		Clarify in the LazyOptional which methods carry the lazyness over to the returned value and which don't. (#6750)
>		
>		For consistency, this meant making a few changes:
>		- Renamed the existing lazy mapping method to lazyMap, to indicate that it doesn't run the mapping immediately.
>		- Added a new implementation of map(), which returns Optional<T>, and resolves the value in the process.
>		- Changed filter() to return Optional, since there's no way to filter lazily.
>		- Added a new method resolve(), which helps convert the custom LazyOptional class into a standard Optional, for use
>		with library methods that expect Optional<T>.
>		
>		* Update License headers.
