### ISSUE TITLE
Worlds don't want to load, weird dots during world generation, clicking the 'Locks' creative inventory tab crashes the game and breaking ANY blocks crashes too

### ISSUE THREAD

**Issue by Catomax262** [Melonslise/Locks#76]
It is weird, because this mod is the only one that can do the4 previous things, which is an devastating effect. What is wrong with the mod? Huh?

**Comment by agentwolf88** [comment]
same

**Comment by Mensh123** [comment]
I had the crashing problem too. I'll quickly rerun the game and provide problem descreptions. Hello @Catomax262, hello @agentwolf88! Please provide further informathion if you open an issue on GitHub

**Comment by Mensh123** [comment]
Forge version: 1.16.5-forge-36.1.0
Locks version: 1.16.12-2.5.2
Java version: 15.0.2
World already played before installation of locks.
Mods I had installed as well: create, journeymap
Crash report:
```
The game crashed whilst rendering item
Error: java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Lnet/minecraftforge/common/util/LazyOptional;
Exit-Code: -1
```
