### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [Melonslise/Locks#79]
Will you update the mod to version 1.16.5, if so when will it be possible?

**Comment by agentwolf88** [comment]
This mod works with 1.16.5!

**Comment by ghost** [comment]
Yes of course, except it crashes the game.

**Comment by ghost** [comment]
Will you update the mod to version 1.16.5, if so, when will it be possible? The current version crashes the world in game version 1.16.5.

**Comment by MercurialPony** [comment]
Please be patient. It's coming soon with a lot of new features too
