### ISSUE TITLE
Enchantment Descriptions Support

### ISSUE THREAD

**Issue by WenXin20** [Melonslise/Locks#81]
This would only require `enchantment.locks.enchant_name.desc` to be added to the lang file.

**Comment by MercurialPony** [comment]
What mod is this for, may I ask?

**Comment by WenXin20** [comment]
The Enchantment Descriptions mod. :D
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by MercurialPony** [comment]
Ok, next update then

**Comment by WenXin20** [comment]
Thanks!
