### ISSUE TITLE
[1.16.5] Crash with Create's ponder feature

### ISSUE THREAD

**Issue by Ritzumi** [Melonslise/Locks#83]
**Description**
Create has a feature to view usage(ponder) tutorial for their components. With this mod installed, trying to use this feature will crash the game. I suspect that the problem caused by the chest that are being rendered in their tutorial.

**How to reproduce**
1. Enter a world
2. Open Create creative tab
3. Press [W] to ponder cogwheel

**Version**
Forge: 36.1.16
Lock: locks-3.0
Create: create-mc1.16.5_v0.3.1c

**Log**
The game does not directly produce crash log. There are some errors in the log, however.
https://gist.github.com/Ritzumi/e26527470b3bc6faf9d24799fdeb061e

P.S. Thank you (´ω｀)

**Comment by MercurialPony** [comment]
Interesting... Looks to me more like a create error, but I'll try to investigate it further soon

**Comment by Ritzumi** [comment]
I wasn't sure about which is the culprit. If it is not on this end then I am so sorry about that ;-; . Thank you anyways!

**Comment by MercurialPony** [comment]
Can you please test the ponder feature with all your current mods, **excluding** the locks mod?

**Comment by Ritzumi** [comment]
I tested with other mods except Locks. Ponder work normally.
I also tested with only Locks and Create. Ponder crashed the game.

**Comment by Melonslise** [comment]
Ok after some investigation it does seem my mod is causing the issue in TemplateMixin#placeInWorld by calling IServerWorld#getLevel(), which throws an error in the Create schematic world. However I don't really know how to fix this and I think it's up to Create to remove the error throwing and return some empty world or whatever. Gonna post this on your Create issue as well to see if we can get a response from the devs

**Comment by MercurialPony** [comment]
I posted the details of the error on your create issue for the devs in case they check it out. Meanwhile I'll add a very basic fix that should at least prevent the crash
