### ISSUE TITLE
Blocks appear to have no blast resistance

### ISSUE THREAD

**Issue by Magnetron64** [Melonslise/Locks#84]
**Description:**
Explosions will destroy any blocks

**How to reproduce:**
Make a world, spawn tnt or creeper, place down obsidian next to it, ignite it, obsidian and other usually unbreakable blocks get destroyed.

**Forge version:**
Forge: 36.1.4

**Mods:**
Lock: locks-3.0

![2021-05-22_18 34 36](https://user-images.githubusercontent.com/74421249/119232052-6a38e200-bb2c-11eb-8161-007ae52e2980.png)

![2021-05-22_18 34 43](https://user-images.githubusercontent.com/74421249/119232070-74f37700-bb2c-11eb-847d-266b2e9450cc.png)

**Comment by NX-HypnicJerk** [comment]
I have encountered the same problem.  While testing I set off a creeper explosion on a superflat creative world and it blew a hole through bedrock:
![image](https://user-images.githubusercontent.com/10928371/119235459-49ef3000-baf8-11eb-97a4-a95d7c74eaeb.png)

I just added the Locks mod yesterday then noticed this behavior.  Removed Locks mod, tested in creative, problem went away.

**Comment by MercurialPony** [comment]
Whoops! Must've screwed up the logic in the explosion mixin. I'll try to release a fix soon but I'm a bit busy at the moment

**Comment by sirben99** [comment]
Hey!

I wanted to add that the explosion size is also messed up. It was driving me crazy that the explosions were huge for no reason, and though troubleshooting i managed to narrow it down to this mod

Vanilla Explosion Strength:
![2021-05-23_19 59 07](https://user-images.githubusercontent.com/32977052/119276232-6dae9500-bc22-11eb-9bf2-efa5ccf67d68.png)

With Locks mod Explosion Strength:
![2021-05-23_23 54 47](https://user-images.githubusercontent.com/32977052/119276245-7f903800-bc22-11eb-887d-f4540e03ec5b.png)

Hope this helps!

Ben
