### ISSUE TITLE
[Request] Multiple Lock Pick Types

### ISSUE THREAD

**Issue by Weznon** [Melonslise/Locks#9]
One feature I would like is having multiple types of lock picks, which would have different breaking chances from one another. [On my fork of the mod ](https://github.com/Weznon/Locks)I added a second type of pick, and it should be generalizeable to other numbers (although the texture changing of the lockpick in the gui does't currently allow for it, it would be a very easy fix to do so). 

Should I submit a pull request? I am unsure of whether my code would be the idiomatic way to add this feature.

**Comment by Melonslise** [comment]
Ok I’ll try to add this in the next update when I’m free. I won’t merge your code, sorry. After glancing over it I found some bugs and whatnot

**Comment by Weznon** [comment]
Great, thanks so much! I imagine there's a lot of bugs in my code; it was more for me to see whether it would be an reasonable request to make.

**Comment by Melonslise** [comment]
Yes, indeed. In fact, you had some good ideas which I’ll certainly take advantage of. So thank you for trying!
